version: "2"
services:
  node:
    image: "balenalib/jetson-nano-debian-node:latest"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8181"
    command: "npm start"
